var data = {
    "type": "FeatureCollection",
    "name": "punts",
    "features": [
       
        
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.16759", "LAT": "41.39215", "tel": "93 215 35 66", "horari": "Dilluns a Divendres: 08:30-15:00, 16:30-20:00, Dissabtes: 09:00-15:00", "nom_operad": "TEISA-Hispano Hilarienca", "direccio": "Carrer Pau Clarís nº 117, 08009 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/Teisa.jpg", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "", "alta_fn_fm": "", "alta_aturat": "", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.16759, 41.39215", "sector": "1", "corona": 1, "URL": "http://www.teisa-bus.com/es/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.16759, 41.39215]] } },
        
        
        { "type": "Feature", "properties": { "poblacio": "Viladecans", "LON": "2.02057", "LAT": "41.31466", "tel": "93 635 71 85", "horari": "Dilluns a Divendres: 08:00-20:00", "nom_operad": "Baixbus", "direccio": "Carretera de la Vila, 08840 (Viladecans)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/Baixbus.png", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "", "alta_fn_fm": "", "alta_aturat": "", "bescanvis_duplicats": "", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.02057, 41.31466", "sector": "1", "corona": 1, "URL": "https://www.baixbus.cat/ca" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.02057, 41.31466]] } },
        
        { "type": "Feature", "properties": { "poblacio": "Ripollet", "LON": "2.16937", "LAT": "41.49526", "tel": "93 580 18 18", "horari": "", "nom_operad": "Autocars R.Font", "direccio": "Carrer Tamarit nº 105, 08291 (Ripollet)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/font.JPG", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "", "alta_fn_fm": "", "alta_aturat": "", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.16937, 41.49526", "sector": "2C", "corona": 2, "URL": "http://www.autocaresfont.es/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.16937, 41.49526]] } },
        
        { "type": "Feature", "properties": { "poblacio": "Badalona", "LON": "2.23297", "LAT": "41.44373", "tel": "93 395 31 11", "horari": "Dilluns a Diumenge: 07:30-20:00", "nom_operad": "Tusgsal", "direccio": "Plaça d'en Joan Miró nº 3, (Badalona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/tusgsal.jpg", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "", "alta_fn_fm": "", "alta_aturat": "", "bescanvis_duplicats": "", "consultes": "X", "factures": "", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.23297, 41.44373", "sector": "1", "corona": 1, "URL": "http://www.tusgsal.cat/cat/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.23297, 41.44373]] } },
        { "type": "Feature", "properties": { "poblacio": "Badalona", "LON": "2.24384", "LAT": "41.46673", "tel": "93 395 31 11", "horari": "Dilluns a Diumenge: 07:30-20:00", "nom_operad": "Tusgsal", "direccio": "Camí de Can Ruti, s\/n (Badalona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/tusgsal.jpg", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "", "alta_fn_fm": "", "alta_aturat": "", "bescanvis_duplicats": "", "consultes": "X", "factures": "", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.24384, 41.46673", "sector": "1", "corona": 1, "URL": "http://www.tusgsal.cat/cat/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.24384, 41.46673]] } },
        
        
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.17006", "LAT": "41.38567", "tel": "", "horari": "Dilluns a Divendres: 08:00-20:00", "nom_operad": "FGC", "direccio": "Plaça de Catalunya, 08001 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/FGC.png", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.17006, 41.38567", "sector": "1", "corona": 1, "URL": "https://www.fgc.cat/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.17006, 41.38567]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.14846", "LAT": "41.37453", "tel": "", "horari": "Dilluns a Divendres: 09:00-14:00, 16:00-18:30", "nom_operad": "FGC", "direccio": "Plaça Espanya, Gran Via de les Corts Catalanes, 8015 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/FGC.png", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.14846, 41.37453", "sector": "1", "corona": 1, "URL": "https://www.fgc.cat/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.14846, 41.37453]] } },
       
        
        
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.18274", "LAT": "41.44472", "tel": "93 261 55 85", "horari": "", "nom_operad": "Autocars Julià", "direccio": "Carrer Pablo Iglesias nº 84, 08908 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/Julia.jpg", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "", "alta_fn_fm": "", "alta_aturat": "", "bescanvis_duplicats": "", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.18274, 41.44472", "sector": "1", "corona": 1, "URL": "https://autocaresjulia.com/ca" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.18274, 41.44472]] } },
        
        
        { "type": "Feature", "properties": { "poblacio": "L'Hospitalet de Llobregat", "LON": "2.13028", "LAT": "41.36140", "tel": "900 928 900", "horari": "Dilluns a Divendres: 08:00 - 20:00, Dissabtes, Diumenges  i festius: 09:00-14:00", "nom_operad": "CENTRE D'ATENCIÓ I INFORMACIÓ T-MOBILITAT", "direccio": "Avinguda de la Granvia de l’Hospitalet nº 16, 08908 (L'Hospitalet de Llobregat)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/t-mob.png", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.13028, 41.36140", "sector": "1", "corona": 1, "URL": "https://t-mobilitat.atm.cat/web/t-mobilitat" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.13028, 41.3614]] } },
        
        
       
        { "type": "Feature", "properties": { "poblacio": "Sant Feliu de Llobregat", "LON": "2.03479", "LAT": "41.39467", "tel": "93 632 51 33", "horari": "Dilluns a Divendres: 09:00-14:00", "nom_operad": "Soler i sauret, Molins Bus, SantVi bus, ValldoreixBus", "direccio": "Ctra. Laureà Miró, 426, 08980 (Sant Feliu de Llobregat)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/solersauret.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "És necessari sol·licitar cita prèvia a través de la web (www.solerisauret.com) o del  telèfon (936325133)", "COORDENADES": "2.03479, 41.39467", "sector": "1", "corona": 1, "URL": "http://www.solerisauret.com/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.03479, 41.39467]] } },
        
        
        { "type": "Feature", "properties": { "poblacio": "Sabadell", "LON": "2.11498", "LAT": "41.54791", "tel": "935806700", "horari": "Dilluns a Divendres: 08:00 a 13:00 a 16:00 a 19:00", "nom_operad": "Sarbus", "direccio": "Carre de l'Estació nº 67, 08202 (Sabadell)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/sarbus.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.11498, 41.54791", "sector": "2C", "corona": 2, "URL": "https://www.moventis.es/ca/Marcas/sarbus" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.11498, 41.54791]] } },
       
        
        
        
        { "type": "Feature", "properties": { "poblacio": "Sant Joan Despí", "LON": "2.06575", "LAT": "41.36795", "tel": "900 70 11 81", "horari": "Dilluns a Divendres: 09:00-19:00 \/ Juliol i Agost de Dll a Dvs: 08:00 a 15:00", "nom_operad": "TRAM", "direccio": "Av. Barcelona s\/n, 08970 (Sant Joan Despí)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/TRAM.jpg", "alta_client": "X", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.06575, 41.36795", "sector": "1", "corona": 1, "URL": "https://www.tram.cat/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.06575, 41.36795]] } },
        { "type": "Feature", "properties": { "poblacio": "Sant Adrià de Besòs", "LON": "2.22580", "LAT": "41.41923", "tel": "900 70 11 81", "horari": "Dilluns a Divendres: 09:00-19:00 \/ Juliol i Agost de Dll a Dvs: 08:00 a 15:00", "nom_operad": "TRAM", "direccio": "Av. Eduard Maristany, s\/n, 08930 (Sant Adrià de Besòs)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/TRAM.jpg", "alta_client": "X", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.22580, 41.41923", "sector": "1", "corona": 1, "URL": "https://www.tram.cat/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.2258, 41.41923]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.16967", "LAT": "41.38735", "tel": "900 41 00 41", "horari": "Dilluns a Divendres 09:00 a 13:00 i 15:00 a 19:00 ", "nom_operad": "Renfe Rodalies de Catalunya", "direccio": "Plaça Catalunya, s\/n 08002 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/renfe.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.16967, 41.38735", "sector": "1", "corona": 1, "URL": "http://rodalies.gencat.cat/ca/inici/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.16967, 41.38735]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.14017", "LAT": "41.37918", "tel": "900 41 00 41", "horari": "Dilluns a Divendres 09:00 a 13:00 i 15:00 a 19:00 ", "nom_operad": "Renfe Rodalies de Catalunya", "direccio": "Plaça dels Països Catalans, s\/n 08014 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/renfe.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.14017, 41.37918", "sector": "1", "corona": 1, "URL": "http://rodalies.gencat.cat/ca/inici/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.14017, 41.37918]] } },
        
        { "type": "Feature", "properties": { "poblacio": "Gavà", "LON": "2.01047", "LAT": "41.30334", "tel": "900 41 00 41", "horari": "Dilluns a Divendres 09:00 a 13:00 i 15:00 a 19:00 ", "nom_operad": "Renfe Rodalies de Catalunya", "direccio": "Salamanca, 1  08850 (Gavà)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/renfe.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.01047, 41.30334", "sector": "1", "corona": 1, "URL": "http://rodalies.gencat.cat/ca/inici/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.01047, 41.30334]] } },
        
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.16533", "LAT": "41.39209", "tel": "900 41 00 41", "horari": "Dilluns a Divendres 09:00 a 13:00 i 15:00 a 19:00 ", "nom_operad": "Renfe Rodalies de Catalunya", "direccio": "Passeig de Gràcia nº 56, 08007 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/renfe.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.16533, 41.39209", "sector": "1", "corona": 1, "URL": "http://rodalies.gencat.cat/ca/inici/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.16533, 41.39209]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.18721", "LAT": "41.40930", "tel": "900 41 00 41", "horari": "Dilluns a Divendres 09:00 a 13:00 i 15:00 a 19:00 ", "nom_operad": "Renfe Rodalies de Catalunya", "direccio": "Plaça Canonge Rodò, s\/n 08027 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/renfe.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.18721, 41.40930", "sector": "1", "corona": 1, "URL": "http://rodalies.gencat.cat/ca/inici/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.18721, 41.4093]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.18309", "LAT": "41.43089", "tel": "900 41 00 41", "horari": "Dilluns a Divendres 09:00 a 13:00 i 15:00 a 19:00 ", "nom_operad": "Renfe Rodalies de Catalunya", "direccio": "Avinguda Meridiana, 416 08027 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/renfe.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.18309, 41.43089", "sector": "1", "corona": 1, "URL": "http://rodalies.gencat.cat/ca/inici/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.18309, 41.43089]] } },
        { "type": "Feature", "properties": { "poblacio": "L'Hospitalet de Llobregat", "LON": "2.10042", "LAT": "41.36412", "tel": "900 41 00 41", "horari": "Dilluns a Divendres 09:00 a 13:00 i 15:00 a 19:00 ", "nom_operad": "Renfe Rodalies de Catalunya", "direccio": "Avinguda Josep Tarradellas,192 08901 (l'Hospitalet)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/renfe.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.10042, 41.36412", "sector": "1", "corona": 1, "URL": "http://rodalies.gencat.cat/ca/inici/index.html" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.10042, 41.36412]] } },
        
       
        { "type": "Feature", "properties": { "poblacio": "Corbera de Llobregat", "LON": "1.91780", "LAT": "41.41499", "tel": "93 650 07 35", "horari": "Dilluns a Divendres: 09:00-17:00", "nom_operad": "Autocorb", "direccio": "Carretera de l'Amunt, 6-8, 08757 (Corbera de Llobregat)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/Autocorb.png", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "", "alta_t16": "", "alta_fn_fm": "", "alta_aturat": "", "bescanvis_duplicats": "X", "consultes": "X", "factures": "", "gestio_usuaris_titols_suports": "", "gestio_incidencies": "X", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "1.91780, 41.41499", "sector": "2B", "corona": 2, "URL": "https://www.autocorb.com/" }, "geometry": { "type": "MultiPoint", "coordinates": [[1.9178, 41.41499]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.16482", "LAT": "41.38593", "tel": "902 07 50 27", "horari": "Dilluns a Divendres: 08:00-20:00, Dissabtes: 09:00-17:30, Festius: 09:00-14:00", "nom_operad": "TMB", "direccio": "Ronda de la Universitat, 08007 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/TMB.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.16482, 41.38593", "sector": "1", "corona": 1, "URL": "https://www.tmb.cat/ca/home" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.16482, 41.38593]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.15879", "LAT": "41.39452", "tel": "902 07 50 27", "horari": "Dilluns a Divendres: 08:00-20:00", "nom_operad": "TMB", "direccio": "Rambla de Catalunya, 08008 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/TMB.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.15879, 41.39452", "sector": "1", "corona": 1, "URL": "https://www.tmb.cat/ca/home" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.15879, 41.39452]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.18708", "LAT": "41.42219", "tel": "902 07 50 27", "horari": "Dilluns a Divendres: 08:00-20:00", "nom_operad": "TMB", "direccio": "Carrer de Honduras, 08027 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/TMB.jpg", "alta_client": "X", "emissio_suport": "X", "carrega_recarrega": "X", "alta_t16": "", "alta_fn_fm": "X", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "X", "gestio_incidencies": "X", "baixa_suport": "X", "baixa_client": "X", "observacions": "", "COORDENADES": "2.18708, 41.42219", "sector": "1", "corona": 1, "URL": "https://www.tmb.cat/ca/home" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.18708, 41.42219]] } },
        
        
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.17428", "LAT": "41.39619", "tel": "93 231 27 56", "horari": "Dilluns a Dissabte: 08:00-22:00", "nom_operad": "Sagalés", "direccio": "Passeig Sant Joan nº 52, 08009 (Barcelona)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/sagales.png", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "", "gestio_incidencies": "", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.17428, 41.39619", "sector": "1", "corona": 1, "URL": "https://www.sagales.com/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.17428, 41.39619]] } },
        { "type": "Feature", "properties": { "poblacio": "Barcelona", "LON": "2.18243", "LAT": "41,39382", "tel": "93 232 04 59", "horari": "Dilluns a Dissabte: 08:00-22:00", "nom_operad": "Sagalés", "direccio": "Barcelona - Estació del Nord (Taquilla C-0) Carrer Ali Bei, 80, 08013 ", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/sagales.png", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "", "gestio_incidencies": "", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.18243, 41,39382", "sector": "1", "corona": 1, "URL": "https://www.sagales.com/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.18243, 41.39382]] } },
       
        
        { "type": "Feature", "properties": { "poblacio": "Mollet del Vallès", "LON": "2.22523", "LAT": "41.55032", "tel": "902 13 00 14", "horari": "Dilluns a Dissabte: 08:00-22:00", "nom_operad": "Sagalés", "direccio": "Carrer FW Sertüner s\/n, 08100 (Mollet del Vallès)", "img": "https:\/\/raw.githubusercontent.com\/GestioTransport\/Geoportal\/master\/Logos\/sagales.png", "alta_client": "", "emissio_suport": "", "carrega_recarrega": "X", "alta_t16": "X", "alta_fn_fm": "", "alta_aturat": "X", "bescanvis_duplicats": "X", "consultes": "X", "factures": "X", "gestio_usuaris_titols_suports": "", "gestio_incidencies": "", "baixa_suport": "", "baixa_client": "", "observacions": "", "COORDENADES": "2.22523, 41.55032", "sector": "2D", "corona": 2, "URL": "https://www.sagales.com/" }, "geometry": { "type": "MultiPoint", "coordinates": [[2.22523, 41.55032]] } }
    ]
}
